name: Build USBFast17

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos
        shell: bash
        run: |
          set -e

          # Install Theos
          git clone --recursive --depth=1 https://github.com/theos/theos.git "$GITHUB_WORKSPACE/theos"

          # Install dm.pl
          git clone --depth=1 https://github.com/theos/dm.pl.git "$GITHUB_WORKSPACE/dm.pl"
          chmod +x "$GITHUB_WORKSPACE/dm.pl/dm.pl"

          # Set Theos environment
          echo "THEOS=$GITHUB_WORKSPACE/theos" >> "$GITHUB_ENV"

          # Put dm.pl into PATH
          echo "$GITHUB_WORKSPACE/dm.pl" >> "$GITHUB_PATH"

          # Check installation
          echo "THEOS=$GITHUB_WORKSPACE/theos"
          echo "dm.pl location:"
          which dm.pl
          dm.pl --help

      - name: Build package
        shell: bash
        run: |
          set -e

          export THEOS="$GITHUB_WORKSPACE/theos"

          echo "THEOS=$THEOS"
          echo "dm.pl location:"
          which dm.pl

          make package FINALPACKAGE=1

      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: USBFast17-deb
          path: packages/*.deb
